# Generated by Django 4.0.6 on 2022-07-16 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(default='0001', max_length=4, verbose_name='Agency')),
                ('account_number', models.CharField(max_length=5, verbose_name='Account')),
                ('account_digit', models.CharField(max_length=1, verbose_name='Digit')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance')),
                ('token', models.CharField(max_length=4, verbose_name='Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Cliente Since')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
