# Generated by Django 4.0.6 on 2022-07-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_digit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_digit',
            field=models.CharField(max_length=1, verbose_name='Digit'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=5, verbose_name='Account'),
        ),
    ]
