# Generated by Django 4.0.6 on 2022-07-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_digit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_digit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Account'),
        ),
    ]
