# Generated by Django 4.0.6 on 2022-07-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='account_id',
            new_name='account_number',
        ),
    ]
