# Generated by Django 4.0.6 on 2022-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
